### ISSUE TITLE
Utilizar lib do Pub/Sub

### ISSUE THREAD

**Issue by arbexmb** [skore-io/nestjs-extensions#85]
Atualmente estamos utilizando a lib do `GoogleAuth` para autenticar, e depois enviamos uma request REST Api para publicar eventos no Pub/Sub: [aqui](https://github.com/skore-io/nestjs-extensions/blob/main/packages/event/src/client/pub-sub.client.ts#L13).

Podemos utilizar a lib oficial do Pub/Sub diretamente. Esta [aqui](https://www.npmjs.com/package/@google-cloud/pubsub).

**Comment by renatoaug** [comment]
Acho que já foi resolvido. Fechando a issue
